import type { MoodboardQuestionSeed } from "./db-types";
import { OUTPUT_SECTIONS } from "./output-sections";

export const MOODBOARD_QUESTION_SEED: MoodboardQuestionSeed[] = [
  {
    key: "q1",
    question_text: "What's the name of the brand or project you're working on?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "brand_basics",
    order_index: 1,
  },
  {
    key: "q2",
    question_text:
      "Tell me a bit about what this brand does. What's the product or service?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "brand_basics",
    order_index: 2,
  },
  {
    key: "q3",
    question_text: "What type of project is this?",
    question_type: "chips",
    parent_key: null,
    chips_options: ["App", "Website", "Brand Identity", "Campaign", "Logo", "Other"],
    follow_up_condition: null,
    category: "brand_basics",
    order_index: 3,
  },
  {
    key: "q4",
    question_text: "Is this a new brand or a redesign/refresh of an existing one?",
    question_type: "chips",
    parent_key: null,
    chips_options: ["New brand", "Redesign/Refresh"],
    follow_up_condition: null,
    category: "brand_basics",
    order_index: 4,
  },
  {
    key: "q4a",
    question_text:
      "Share the existing website or app link — I'll take a look at what's there.",
    question_type: "url",
    parent_key: "q4",
    chips_options: null,
    follow_up_condition: "Redesign/Refresh",
    category: "brand_basics",
    order_index: 5,
  },
  {
    key: "q4b",
    question_text:
      "What's not working with the current design? What made you decide it needs a refresh?",
    question_type: "open",
    parent_key: "q4a",
    chips_options: null,
    follow_up_condition: null,
    category: "brand_basics",
    order_index: 6,
  },
  {
    key: "q5",
    question_text: "What industry or sector is this in?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "market_context",
    order_index: 7,
  },
  {
    key: "q6",
    question_text:
      "Who is the primary target audience? Describe them — age, lifestyle, mindset, what they care about.",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "user_persona",
    order_index: 8,
  },
  {
    key: "q7",
    question_text:
      "Are there multiple user types or personas we should design for? If yes, describe them.",
    question_type: "chips",
    parent_key: null,
    chips_options: ["Just one type", "2 personas", "3+ personas"],
    follow_up_condition: null,
    category: "user_persona",
    order_index: 9,
  },
  {
    key: "q8",
    question_text:
      "What are the biggest pain points your users currently face — with the product or with competitors?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "user_persona",
    order_index: 10,
  },
  {
    key: "q9",
    question_text: "What does your target user aspire to feel when using this product?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "user_persona",
    order_index: 11,
  },
  {
    key: "q10",
    question_text: "Who are your top 3 competitors? Name them.",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "competitive",
    order_index: 12,
  },
  {
    key: "q11",
    question_text:
      "What do you like about competitors? What do you NOT want to be like?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "competitive",
    order_index: 13,
  },
  {
    key: "q12",
    question_text:
      "Are there any brands outside your category whose visual style or personality you admire? Why?",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "references",
    order_index: 14,
  },
  {
    key: "q13",
    question_text:
      "Upload any reference images — logos, websites, apps, campaigns — that feel right for this brand. Or describe them.",
    question_type: "upload",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "references",
    order_index: 15,
  },
  {
    key: "q14",
    question_text: "How should this brand feel? Choose what resonates.",
    question_type: "chips",
    parent_key: null,
    chips_options: [
      "Minimal",
      "Bold",
      "Warm",
      "Premium",
      "Playful",
      "Serious",
      "Human",
      "Technical",
      "Raw",
      "Refined",
      "Loud",
      "Quiet",
      "Modern",
      "Timeless",
      "Energetic",
      "Calm",
    ],
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 16,
  },
  {
    key: "q15",
    question_text: "Color direction — what feels right?",
    question_type: "chips",
    parent_key: null,
    chips_options: [
      "Warm tones",
      "Cool tones",
      "Neutral/muted",
      "Dark/dramatic",
      "Light/airy",
      "Vibrant/saturated",
      "Open to AI",
    ],
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 17,
  },
  {
    key: "q16",
    question_text: "Typography personality?",
    question_type: "chips",
    parent_key: null,
    chips_options: [
      "Clean sans-serif",
      "Strong/bold",
      "Elegant serif",
      "Friendly/rounded",
      "Technical/mono",
      "Open to AI",
    ],
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 18,
  },
  {
    key: "q17",
    question_text: "Illustration or photography style?",
    question_type: "chips",
    parent_key: null,
    chips_options: [
      "Flat illustrations",
      "3D illustrations",
      "Real photography",
      "Abstract/graphic",
      "No imagery",
      "Open to AI",
    ],
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 19,
  },
  {
    key: "q18",
    question_text:
      "Any specific things to AVOID? Colors, styles, clichés that feel wrong.",
    question_type: "open",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 20,
  },
  {
    key: "q19",
    question_text:
      "Last one — do you have a brand questionnaire or brief you'd like me to read? Upload it here.",
    question_type: "upload",
    parent_key: null,
    chips_options: null,
    follow_up_condition: null,
    category: "visual_direction",
    order_index: 21,
  },
  {
    key: "q_output_sections",
    question_text:
      "Almost there! What should your moodboard cover?\nSelect the sections you want included.",
    question_type: "multi_section_select",
    parent_key: null,
    chips_options: OUTPUT_SECTIONS,
    follow_up_condition: null,
    category: "output_sections",
    order_index: 22,
  },
  {
    key: "q_output_product_type",
    question_text: "What kind of products?",
    question_type: "chips",
    parent_key: "q_output_sections",
    chips_options: [
      "Fashion",
      "Electronics",
      "Food & Beverage",
      "Beauty",
      "Home & Living",
      "Other",
    ],
    follow_up_condition: "product_images",
    category: "output_sections",
    order_index: 23,
  },
  {
    key: "q_output_illustration_style",
    question_text: "What illustration style feels right?",
    question_type: "chips",
    parent_key: "q_output_sections",
    chips_options: [
      "Flat",
      "3D",
      "Hand-drawn",
      "Abstract",
      "Minimal line",
      "Open to AI",
    ],
    follow_up_condition: "illustration_style",
    category: "output_sections",
    order_index: 24,
  },
  {
    key: "q_output_icon_style",
    question_text: "Icon style preference?",
    question_type: "chips",
    parent_key: "q_output_sections",
    chips_options: ["Outlined", "Filled", "Duotone", "Bold/thick", "Open to AI"],
    follow_up_condition: "icon_library",
    category: "output_sections",
    order_index: 25,
  },
];

export const OPTIONAL_QUESTION_KEYS = new Set(["q13", "q18", "q19"]);
export const MULTI_SELECT_KEYS = new Set(["q14"]);
export const UPLOAD_WITH_OPEN_KEYS = new Set(["q4b", "q13"]);
export const OPEN_WITH_UPLOAD_KEYS = new Set(["q4b"]);
export const MAX_REFERENCE_IMAGES = 10;

export const QUESTION_STEP_MAP: Record<string, number> = {
  q1: 1,
  q2: 2,
  q3: 3,
  q4: 4,
  q4a: 4,
  q4b: 4,
  q5: 5,
  q6: 6,
  q7: 7,
  q8: 8,
  q9: 9,
  q10: 10,
  q11: 11,
  q12: 12,
  q13: 13,
  q14: 14,
  q15: 15,
  q16: 16,
  q17: 17,
  q18: 18,
  q19: 19,
};

export const TOTAL_QUESTION_STEPS = 19;
